version: "3.9"

services:
  # 🐘 Banco de Dados PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"

  # 🚀 Aplicação Django
  app:
    #producao
    image: carlos98770/django_rest-api:latest
    container_name: app_app_1
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"  

    #desenvolvimento
    # build: .
    # volumes:
    #   - .:/app
    # env_file:
    #   - .env
    # depends_on:
    #   - db
    # ports:
    #   - "8000:8000"
    

volumes:
  postgres_data:
