version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: lacrei_saude
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: django_app_lacrei
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_NAME: simas
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
