# Generated by Django 5.2.7 on 2025-10-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_consultas_delete_consultation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profissional",
            name="professional_register",
            field=models.CharField(max_length=50),
        ),
    ]
